parameters:
  overcloud_flavor: m1.large
  overcloud_image: CentOS-7-x86_64-GenericCloud-1708
  key_name: jslagle-rdo-cloud
  private_net: private
  overcloud_node_count: 1
  public_net:  38.145.32.0/22
  undercloud_image: CentOS-7-x86_64-GenericCloud-1708
  undercloud_flavor: m1.large
  toci_jobtype: multinode-1ctlr-featureset010
  zuul_changes: openstack/tripleo-quickstart-extras:master:refs/changes/41/516841/8^openstack/tripleo-common:master:refs/changes/75/512875/4^openstack/tripleo-common:master:refs/changes/76/512876/12^openstack/python-tripleoclient:master:refs/changes/01/514701/8^openstack/tripleo-common:master:refs/changes/83/514783/9^openstack/tripleo-common:master:refs/changes/84/514784/9^openstack/python-tripleoclient:master:refs/changes/89/514789/9^openstack/tripleo-quickstart:master:refs/changes/36/514736/11
